[project]
name = 'Ocean-Conservation-and-Maritime-Governance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.illegal-fishing-prevention]
path = 'contracts/illegal-fishing-prevention.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
